name: MSBuild

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    strategy:
      matrix:
        configuration: [Debug, Release]

    runs-on: windows-2019

    steps:
    - uses: actions/checkout@v4
    - name: Add msbuild to PATH
      uses: microsoft/setup-msbuild@v2
    - name: Build
      working-directory: ${{env.GITHUB_WORKSPACE}}
      run: MSBuild.exe .\NETMediaPresenter.csproj
    - uses: actions/upload-artifact@v4
      with:
        name: ${{ matrix.configuration }}\NETMediaPresenter.exe
        path: bin\${{ matrix.configuration }}\NETMediaPresenter.exe
